-- Generated by tools/unify/to_sql.py. Step 4 of 4.
with s as (select split_part(line, '|', 1) as i, split_part(line, '|', 2) as e, nullif(split_part(line, '|', 3), '') as l
           from public.unify_staging)
update public.exercise_variants v set exercise_id = s.e, variant_label = s.l from s where s.i = v.id;

with s as (select split_part(line, '|', 1) as i, nullif(split_part(line, '|', 4), '') as d from public.unify_staging)
update public.exercise_variants v set duplicate_of = s.d from s where s.i = v.id and s.d is not null;

insert into public.variant_equipment (variant_id, equipment_id)
select split_part(line, '|', 1), q from public.unify_staging, string_to_table(split_part(line, '|', 5), '+') q where q <> '';

insert into public.variant_attributes (variant_id, dimension_id, value)
select split_part(line, '|', 1), split_part(a, '=', 1), split_part(a, '=', 2)
from public.unify_staging, string_to_table(split_part(line, '|', 6), ',') a where a <> '';

-- Primary muscle: the node the most common target term maps to (null when it maps to a functional set).
update public.exercises x set primary_muscle_id = a.muscle_id from public.muscle_aliases a where a.term = x.primary_target_term;

select public.rebuild_variant_names();
drop table public.unify_staging;

select (select count(*) from public.exercises) as exercises,
       (select count(*) from public.exercises where is_canonical) as canonical,
       (select count(*) from public.exercise_variants where exercise_id is null) as variants_unlinked,
       (select count(*) from public.exercise_variants where duplicate_of is not null) as duplicates,
       (select count(*) from public.variant_attributes) as attribute_links,
       (select count(*) from public.variant_equipment) as equipment_links;
