#!/usr/bin/env python3
"""Turn tools/unify/proposal.json into SQL that loads the unification into Supabase.

    python3 tools/unify/to_sql.py

Writes supabase/seed/unification/NN_*.sql, to be run in order. Variation rows are sent as compact
pipe-separated text and parsed by Postgres, so each file stays small enough to run through the
SQL editor or the Supabase MCP. Safe to re-run: step 01 clears the previous unification data.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(REPO, 'supabase', 'seed', 'unification')
p = json.load(open(os.path.join(HERE, 'proposal.json'), encoding='utf-8'))


def lit(obj):
    return "'" + json.dumps(obj, ensure_ascii=False, separators=(',', ':')).replace("'", "''") + "'::jsonb"


def txt(s):
    return "'" + s.replace("'", "''") + "'"


equipment = [{'id': k, 'names': v, 'sort_order': i} for i, (k, v) in enumerate(p['equipment'].items())]
dims = [{'id': d, 'names': {'en': v['en'], 'es': v['es']}, 'sort_order': i} for i, (d, v) in enumerate(p['dimensions'].items())]
values = [{'dimension_id': d, 'value': k, 'names': n, 'sort_order': j}
          for d, v in p['dimensions'].items() for j, (k, n) in enumerate(v['values'].items())]
# id|type|canonical(1/0)|en|es|primary target term
ex_lines = ['|'.join([e['id'], e['type'], '1' if e['canonical'] else '0', e['names']['en'], e['names']['es'] or '', e['primary_target']])
            for e in p['exercises']]
# variant id|exercise id|label|duplicate_of|equipment+equipment|dim=value,dim=value
var_lines = ['|'.join([v['id'], v['exercise_id'], v['variant_label'] or '', v.get('duplicate_of') or '', '+'.join(v['equipment']),
                       ','.join(f'{d}={x}' for d, xs in v['attributes'].items() for x in xs)]) for v in p['variants']]

steps = {}
steps['01_reset_and_vocabulary.sql'] = f"""-- Generated by tools/unify/to_sql.py from {p['source']}. Step 1 of 4.
delete from public.variant_attributes;
delete from public.variant_equipment;
update public.exercise_variants set exercise_id = null, variant_label = null, duplicate_of = null, names = null;
delete from public.exercises;
delete from public.variation_values;
delete from public.variation_dimensions;
delete from public.equipment;

insert into public.equipment (id, names, sort_order)
select * from jsonb_to_recordset({lit(equipment)}) as x(id text, names jsonb, sort_order smallint);
insert into public.variation_dimensions (id, names, sort_order)
select * from jsonb_to_recordset({lit(dims)}) as x(id text, names jsonb, sort_order smallint);
insert into public.variation_values (dimension_id, value, names, sort_order)
select * from jsonb_to_recordset({lit(values)}) as x(dimension_id text, value text, names jsonb, sort_order smallint);

insert into public.exercises (id, type, names, is_canonical, primary_target_term, sort_order)
select split_part(l, '|', 1), split_part(l, '|', 2)::public.exercise_type,
       jsonb_strip_nulls(jsonb_build_object('en', split_part(l, '|', 4), 'es', nullif(split_part(l, '|', 5), ''))),
       split_part(l, '|', 3) = '1', split_part(l, '|', 6), (n - 1)::smallint
from string_to_table({txt(chr(10).join(ex_lines))}, chr(10)) with ordinality t(l, n);

drop table if exists public.unify_staging;
create table public.unify_staging (line text not null);  -- dropped in step 4
alter table public.unify_staging enable row level security;
"""
half = len(var_lines) // 2
for n, chunk in ((2, var_lines[:half]), (3, var_lines[half:])):
    steps[f'0{n}_variants_part{n - 1}.sql'] = (f"-- Generated by tools/unify/to_sql.py. Step {n} of 4.\n"
        f"insert into public.unify_staging (line) select l from string_to_table({txt(chr(10).join(chunk))}, chr(10)) l;\n")
steps['04_apply.sql'] = """-- Generated by tools/unify/to_sql.py. Step 4 of 4.
with s as (select split_part(line, '|', 1) as i, split_part(line, '|', 2) as e, nullif(split_part(line, '|', 3), '') as l
           from public.unify_staging)
update public.exercise_variants v set exercise_id = s.e, variant_label = s.l from s where s.i = v.id;

with s as (select split_part(line, '|', 1) as i, nullif(split_part(line, '|', 4), '') as d from public.unify_staging)
update public.exercise_variants v set duplicate_of = s.d from s where s.i = v.id and s.d is not null;

insert into public.variant_equipment (variant_id, equipment_id)
select split_part(line, '|', 1), q from public.unify_staging, string_to_table(split_part(line, '|', 5), '+') q where q <> '';

insert into public.variant_attributes (variant_id, dimension_id, value)
select split_part(line, '|', 1), split_part(a, '=', 1), split_part(a, '=', 2)
from public.unify_staging, string_to_table(split_part(line, '|', 6), ',') a where a <> '';

-- Primary muscle: the node the most common target term maps to (null when it maps to a functional set).
update public.exercises x set primary_muscle_id = a.muscle_id from public.muscle_aliases a where a.term = x.primary_target_term;

select public.rebuild_variant_names();
drop table public.unify_staging;

select (select count(*) from public.exercises) as exercises,
       (select count(*) from public.exercises where is_canonical) as canonical,
       (select count(*) from public.exercise_variants where exercise_id is null) as variants_unlinked,
       (select count(*) from public.exercise_variants where duplicate_of is not null) as duplicates,
       (select count(*) from public.variant_attributes) as attribute_links,
       (select count(*) from public.variant_equipment) as equipment_links;
"""
os.makedirs(OUT, exist_ok=True)
old = os.path.join(REPO, 'supabase', 'seed', 'load_unification.sql')
if os.path.exists(old):
    os.remove(old)
for name, sql in steps.items():
    with open(os.path.join(OUT, name), 'w', encoding='utf-8') as f:
        f.write(sql)
    print(f'{name:32} {len(sql.encode()) // 1024:4} KB')
