#!/usr/bin/env python3
"""Build web/shared/body-paths.js — the anatomical SVG paths for the body map.

    python3 tools/fetch_body_paths.py

Source: react-native-body-highlighter (MIT, © 2022 ELABBASSI Hicham), pinned to a commit.
Only the vector data is taken: one entry per muscle slug, split into front and back views.
The MIT licence requires the copyright notice to travel with the paths, so it is written into
the generated file's header.
"""
import json
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, 'web', 'shared', 'body-paths.js')
SRC = 'https://raw.githubusercontent.com/HichamELBSI/react-native-body-highlighter'
REF = 'main'            # replaced with the resolved commit below
FILES = {'front': 'assets/bodyFront.ts', 'back': 'assets/bodyBack.ts'}
VIEWBOX = {'front': '0 0 724 1448', 'back': '724 0 724 1448'}


def fetch(url):
    return subprocess.run(['curl', '-sfL', url], capture_output=True, text=True, check=True).stdout


def parse(ts):
    """slug -> list of path 'd' strings (left and right sides merged)."""
    out = {}
    blocks = re.split(r'\n\s*\{\s*\n\s*slug:', ts)
    for block in blocks[1:]:
        slug = re.match(r'\s*"([a-z-]+)"', block).group(1)
        paths = re.findall(r'"([Mm][^"]{20,})"', block)
        if paths:
            out.setdefault(slug, []).extend(paths)
    return out


commit = json.loads(fetch('https://api.github.com/repos/HichamELBSI/react-native-body-highlighter/commits/main'))['sha']
data = {view: parse(fetch(f'{SRC}/{commit}/{path}')) for view, path in FILES.items()}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, 'w', encoding='utf-8') as f:
    f.write(f'''// Generated by tools/fetch_body_paths.py — do not edit by hand.
//
// Anatomical SVG paths from react-native-body-highlighter, commit {commit[:12]}.
// MIT License, Copyright (c) 2022 ELABBASSI Hicham.
// https://github.com/HichamELBSI/react-native-body-highlighter
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute,
// sublicense, and/or sell copies of the Software, subject to the above copyright notice and this
// permission notice being included in all copies or substantial portions of the Software.

export const VIEWBOX = {json.dumps(VIEWBOX)};
export const PATHS = {json.dumps(data, ensure_ascii=False)};
''')

print(f'Wrote {os.path.relpath(OUT, REPO)}')
for view, slugs in data.items():
    print(f'  {view}: {len(slugs)} parts — {", ".join(sorted(slugs))}')
print(f'  {os.path.getsize(OUT) // 1024} KB, source commit {commit[:12]}')
