-- DRAFT data for review by a trainer: movement patterns per exercise, and muscle emphasis rules.
-- Everything here is marked 'drafted' / 'inferred'. Reviewing a row means setting
-- pattern_source = 'reviewed' (exercises) or confidence = 'reviewed' (emphasis_rules).

insert into public.movement_patterns (id, names, plane, sort_order) values
  ('push-horizontal', '{"en":"Horizontal push","es":"Empuje horizontal"}', 'push', 1),
  ('push-vertical',   '{"en":"Vertical push","es":"Empuje vertical"}', 'push', 2),
  ('pull-horizontal', '{"en":"Horizontal pull","es":"Tirón horizontal"}', 'pull', 3),
  ('pull-vertical',   '{"en":"Vertical pull","es":"Tirón vertical"}', 'pull', 4),
  ('squat',           '{"en":"Squat","es":"Sentadilla"}', 'lower', 5),
  ('hinge',           '{"en":"Hip hinge","es":"Bisagra de cadera"}', 'lower', 6),
  ('lunge',           '{"en":"Lunge / step","es":"Zancada / paso"}', 'lower', 7),
  ('leg-isolation',   '{"en":"Knee isolation","es":"Aislamiento de rodilla"}', 'lower', 8),
  ('hip-isolation',   '{"en":"Hip isolation","es":"Aislamiento de cadera"}', 'lower', 9),
  ('calf',            '{"en":"Calf / ankle","es":"Pantorrilla / tobillo"}', 'lower', 10),
  ('elbow-flexion',   '{"en":"Elbow flexion","es":"Flexión de codo"}', 'push', 11),
  ('elbow-extension', '{"en":"Elbow extension","es":"Extensión de codo"}', 'push', 12),
  ('shoulder-isolation', '{"en":"Shoulder isolation","es":"Aislamiento de hombro"}', 'push', 13),
  ('scapular',        '{"en":"Scapular","es":"Escapular"}', 'pull', 14),
  ('core-flexion',    '{"en":"Trunk flexion","es":"Flexión del tronco"}', 'core', 15),
  ('core-rotation',   '{"en":"Trunk rotation","es":"Rotación del tronco"}', 'core', 16),
  ('core-lateral',    '{"en":"Side bend","es":"Flexión lateral"}', 'core', 17),
  ('core-brace',      '{"en":"Anti-movement (brace)","es":"Antimovimiento (estabilidad)"}', 'core', 18),
  ('carry',           '{"en":"Loaded carry","es":"Transporte con carga"}', 'whole-body', 19),
  ('olympic',         '{"en":"Olympic lift","es":"Levantamiento olímpico"}', 'whole-body', 20),
  ('throw',           '{"en":"Throw / slam","es":"Lanzamiento"}', 'whole-body', 21),
  ('gymnastic',       '{"en":"Gymnastic hold","es":"Posición gimnástica"}', 'whole-body', 22),
  ('forearm',         '{"en":"Wrist and grip","es":"Muñeca y agarre"}', 'push', 23);

-- Pattern + mechanics per canonical exercise -----------------------------------------------------
update public.exercises x set movement_pattern = d.pattern, mechanics = d.mech, pattern_source = 'drafted'
from (values
  ('bench-press','push-horizontal','compound'), ('push-up','push-horizontal','compound'),
  ('chest-fly','push-horizontal','isolation'), ('chest-dip','push-vertical','compound'),
  ('overhead-press','push-vertical','compound'), ('triceps-dip','push-vertical','compound'),
  ('handstand','gymnastic','compound'), ('thruster','push-vertical','compound'),
  ('row','pull-horizontal','compound'), ('rear-delt-row','pull-horizontal','compound'),
  ('pull-up','pull-vertical','compound'), ('lat-pulldown','pull-vertical','compound'),
  ('muscle-up','pull-vertical','compound'), ('straight-arm-pulldown','pull-vertical','isolation'),
  ('pullover','pull-vertical','isolation'),
  ('squat','squat','compound'), ('split-squat','squat','compound'), ('sissy-squat','squat','isolation'),
  ('squat-jump','squat','compound'), ('leg-press','squat','compound'), ('lunge','lunge','compound'),
  ('step-up','lunge','compound'),
  ('deadlift','hinge','compound'), ('good-morning','hinge','compound'), ('back-extension','hinge','isolation'),
  ('reverse-hyperextension','hinge','isolation'), ('pull-through','hinge','compound'),
  ('kettlebell-swing','hinge','compound'), ('hip-thrust','hinge','compound'),
  ('leg-extension','leg-isolation','isolation'), ('leg-curl','leg-isolation','isolation'),
  ('hip-abduction','hip-isolation','isolation'), ('hip-adduction','hip-isolation','isolation'),
  ('hip-extension','hip-isolation','isolation'), ('hip-rotation','hip-isolation','isolation'),
  ('calf-raise','calf','isolation'), ('tibialis-raise','calf','isolation'),
  ('biceps-curl','elbow-flexion','isolation'),
  ('triceps-extension','elbow-extension','isolation'), ('triceps-pushdown','elbow-extension','isolation'),
  ('triceps-kickback','elbow-extension','isolation'),
  ('lateral-raise','shoulder-isolation','isolation'), ('front-raise','shoulder-isolation','isolation'),
  ('rear-delt-fly','shoulder-isolation','isolation'), ('y-raise','shoulder-isolation','isolation'),
  ('shoulder-rotation','shoulder-isolation','isolation'), ('upright-row','shoulder-isolation','compound'),
  ('shrug','scapular','isolation'), ('shoulder-raise','scapular','isolation'),
  ('crunch','core-flexion','isolation'), ('sit-up','core-flexion','isolation'),
  ('reverse-crunch','core-flexion','isolation'), ('leg-raise','core-flexion','isolation'),
  ('v-up','core-flexion','isolation'),
  ('russian-twist','core-rotation','isolation'), ('windmill','core-rotation','compound'),
  ('side-bend','core-lateral','isolation'),
  ('plank','core-brace','isolation'), ('ab-rollout','core-brace','isolation'),
  ('dead-bug','core-brace','isolation'), ('pallof-press','core-brace','isolation'),
  ('carry','carry','compound'),
  ('clean','olympic','compound'), ('clean-and-jerk','olympic','compound'),
  ('jerk','olympic','compound'), ('snatch','olympic','compound'),
  ('slam','throw','compound'),
  ('planche','gymnastic','compound'), ('front-lever','gymnastic','compound'),
  ('back-lever','gymnastic','compound'), ('maltese','gymnastic','compound'),
  ('human-flag','gymnastic','compound'),
  ('wrist-curl','forearm','isolation'), ('reverse-wrist-curl','forearm','isolation'),
  ('finger-curl','forearm','isolation'), ('forearm-rotation','forearm','isolation'),
  ('grip-squeeze','forearm','isolation'), ('wrist-roller','forearm','isolation')
) as d(id, pattern, mech) where x.id = d.id;

-- Non-strength exercises keep their type as their pattern; they are not substituted by movement.
update public.exercises set pattern_source = 'drafted' where type <> 'strength' and pattern_source = 'unset';

-- Emphasis rules --------------------------------------------------------------------------------
-- "On this kind of exercise, this attribute changes which muscles do the work."
insert into public.emphasis_rules (id, dimension_id, value, muscle_id, effect, applies_patterns, applies_exercises, notes, sort_order) values
  ('incline-upper-chest', 'bench_angle', 'incline', 'pectoralis-major-clavicular', 'primary', '{push-horizontal}', null,
   '{"en":"Emphasis moves to the upper chest","es":"El énfasis pasa al pecho superior"}', 1),
  ('incline-front-delt', 'bench_angle', 'incline', 'anterior-deltoid', 'more', '{push-horizontal}', null,
   '{"en":"More front shoulder","es":"Más deltoides frontal"}', 2),
  ('decline-lower-chest', 'bench_angle', 'decline', 'pectoralis-major-sternal', 'primary', '{push-horizontal}', null,
   '{"en":"Emphasis moves to the lower chest","es":"El énfasis pasa al pecho inferior"}', 3),
  ('decline-less-delt', 'bench_angle', 'decline', 'anterior-deltoid', 'less', '{push-horizontal}', null,
   '{"en":"Less front shoulder","es":"Menos deltoides frontal"}', 4),
  ('close-grip-triceps', 'grip_width', 'close', 'triceps-brachii', 'more', '{push-horizontal,push-vertical}', null,
   '{"en":"More triceps","es":"Más tríceps"}', 5),
  ('close-grip-less-chest', 'grip_width', 'close', 'pectorals', 'less', '{push-horizontal}', null,
   '{"en":"Less chest","es":"Menos pecho"}', 6),
  ('wide-grip-chest', 'grip_width', 'wide', 'pectorals', 'more', '{push-horizontal}', null,
   '{"en":"More chest, shorter range","es":"Más pecho, recorrido más corto"}', 7),
  ('wide-grip-lats', 'grip_width', 'wide', 'latissimus-dorsi', 'more', '{pull-vertical}', null,
   '{"en":"More lats","es":"Más dorsales"}', 8),
  ('wide-grip-less-biceps', 'grip_width', 'wide', 'biceps-brachii', 'less', '{pull-vertical}', null,
   '{"en":"Less biceps","es":"Menos bíceps"}', 9),
  ('close-grip-pull-biceps', 'grip_width', 'close', 'biceps-brachii', 'more', '{pull-vertical,pull-horizontal}', null,
   '{"en":"More biceps","es":"Más bíceps"}', 10),
  ('supinated-biceps', 'grip', 'supinated', 'biceps-brachii', 'more', '{pull-vertical,pull-horizontal}', null,
   '{"en":"Underhand grip brings in the biceps","es":"El agarre supino implica más al bíceps"}', 11),
  ('neutral-curl-brachialis', 'grip', 'neutral', 'brachialis', 'more', '{elbow-flexion}', null,
   '{"en":"Hammer grip works the brachialis and forearm","es":"El agarre martillo trabaja el braquial y el antebrazo"}', 12),
  ('pronated-curl-forearm', 'grip', 'pronated', 'forearm-extensors', 'more', '{elbow-flexion}', null,
   '{"en":"Reverse grip shifts work to the forearms","es":"El agarre prono lleva el trabajo a los antebrazos"}', 13),
  ('pronated-curl-less-biceps', 'grip', 'pronated', 'biceps-brachii', 'less', '{elbow-flexion}', null,
   '{"en":"Less biceps","es":"Menos bíceps"}', 14),
  ('neutral-press-triceps', 'grip', 'neutral', 'triceps-brachii', 'more', '{push-horizontal}', null,
   '{"en":"More triceps, and easier on the shoulder joint","es":"Más tríceps y más cómodo para el hombro"}', 15),
  ('preacher-no-swing', 'style', 'preacher', 'anterior-deltoid', 'less', '{elbow-flexion}', null,
   '{"en":"The bench stops the shoulder helping","es":"El banco evita que ayude el hombro"}', 16),
  ('concentration-isolate', 'style', 'concentration', 'biceps-brachii', 'more', '{elbow-flexion}', null,
   '{"en":"Isolates the biceps, no help from the body","es":"Aísla el bíceps, sin ayuda del cuerpo"}', 17),
  ('overhead-long-head', 'style', 'overhead', 'triceps-long-head', 'primary', '{elbow-extension}', null,
   '{"en":"Overhead position stretches the long head","es":"La posición sobre la cabeza estira la cabeza larga"}', 18),
  ('behind-neck-side-delt', 'style', 'behind-neck', 'lateral-deltoid', 'more', '{push-vertical}', null,
   '{"en":"More side shoulder, needs shoulder mobility","es":"Más deltoides lateral; exige movilidad de hombro"}', 19),
  ('front-squat-quads', 'style', 'front', 'quadriceps', 'more', '{squat}', null,
   '{"en":"More upright: more quads","es":"Más erguido: más cuádriceps"}', 20),
  ('front-squat-core', 'style', 'front', 'abdominals', 'adds', '{squat}', null,
   '{"en":"The trunk works to stay upright","es":"El tronco trabaja para mantenerse erguido"}', 21),
  ('hack-quads', 'style', 'hack', 'quadriceps', 'more', '{squat}', null,
   '{"en":"More quads, less lower back","es":"Más cuádriceps, menos zona lumbar"}', 22),
  ('sumo-adductors', 'stance', 'sumo', 'adductors', 'more', '{squat,hinge}', null,
   '{"en":"Wide stance brings in the inner thigh","es":"La postura abierta implica la cara interna del muslo"}', 23),
  ('narrow-quads', 'stance', 'narrow', 'quadriceps', 'more', '{squat}', null,
   '{"en":"Narrow stance: more quads","es":"Postura estrecha: más cuádriceps"}', 24),
  ('romanian-hamstrings', 'style', 'romanian', 'hamstrings', 'primary', '{hinge}', null,
   '{"en":"Straighter legs: the hamstrings take the load","es":"Piernas más rectas: los isquiotibiales asumen la carga"}', 25),
  ('stiff-leg-hamstrings', 'style', 'stiff-leg', 'hamstrings', 'primary', '{hinge}', null,
   '{"en":"Straight legs: more hamstring stretch","es":"Piernas rectas: más estiramiento del isquiotibial"}', 26),
  ('one-arm-obliques', 'laterality', 'one-arm', 'obliques', 'adds', null, null,
   '{"en":"One side at a time: the core resists the twist","es":"Un lado cada vez: el core resiste la rotación"}', 27),
  ('single-leg-glute-med', 'laterality', 'single-leg', 'gluteus-medius', 'adds', '{squat,lunge,hinge}', null,
   '{"en":"Balancing on one leg works the side glute","es":"El equilibrio a una pierna trabaja el glúteo medio"}', 28),
  ('standing-brace', 'position', 'standing', 'erector-spinae', 'adds', '{push-vertical,elbow-flexion}', null,
   '{"en":"Standing adds trunk stabilisation","es":"De pie añade estabilización del tronco"}', 29),
  ('push-press-legs', 'style', 'push-press', 'quadriceps', 'adds', '{push-vertical}', null,
   '{"en":"Leg drive helps the press","es":"El impulso de piernas ayuda al press"}', 30),
  ('prone-incline-curl-stretch', 'position', 'prone', 'biceps-brachii', 'more', '{elbow-flexion}', null,
   '{"en":"Arms behind the body: the long head is stretched","es":"Brazos detrás del cuerpo: se estira la porción larga"}', 31),
  ('decline-crunch-lower', 'bench_angle', 'decline', 'rectus-abdominis-lower', 'more', '{core-flexion}', null,
   '{"en":"More lower abs","es":"Más abdominales inferiores"}', 32),
  ('hanging-lower-abs', 'position', 'hanging', 'rectus-abdominis-lower', 'primary', '{core-flexion}', null,
   '{"en":"Hanging and lifting the legs targets the lower abs","es":"Colgado y elevando piernas trabaja el abdomen inferior"}', 33),
  ('twisting-obliques', 'style', 'twisting', 'obliques', 'more', '{core-flexion,core-rotation}', null,
   '{"en":"Twisting brings in the obliques","es":"El giro implica los oblicuos"}', 34);
