-- Muscle taxonomy seed (English + Spanish). Design and open decisions: docs/muscle-taxonomy.md

-- id, level, kind, parent, sort, en, es, common en, common es
insert into public.muscles (id, level, kind, parent_id, sort_order, names, common_names)
select id, level::public.muscle_level, kind::public.muscle_kind, parent, sort,
       jsonb_build_object('en', en, 'es', es),
       case when cen is null then null else jsonb_build_object('en', cen, 'es', ces) end
from (values
  -- Regions
  ('neck','region','muscle',null,1,'Neck','Cuello',null,null),
  ('shoulders','region','muscle',null,2,'Shoulders','Hombros',null,null),
  ('chest','region','muscle',null,3,'Chest','Pecho',null,null),
  ('back','region','muscle',null,4,'Back','Espalda',null,null),
  ('arms','region','muscle',null,5,'Arms','Brazos',null,null),
  ('abdomen','region','muscle',null,6,'Abdomen','Abdomen',null,null),
  ('hips','region','muscle',null,7,'Hips','Cadera',null,null),
  ('legs','region','muscle',null,8,'Legs','Piernas',null,null),
  -- Neck
  ('neck-muscles','group','muscle','neck',1,'Neck muscles','Músculos del cuello',null,null),
  ('sternocleidomastoid','muscle','muscle','neck-muscles',1,'Sternocleidomastoid','Esternocleidomastoideo',null,null),
  ('levator-scapulae','muscle','muscle','neck-muscles',2,'Levator scapulae','Elevador de la escápula',null,null),
  ('splenius','muscle','muscle','neck-muscles',3,'Splenius','Esplenio',null,null),
  -- Shoulders
  ('deltoids','group','muscle','shoulders',1,'Deltoids','Deltoides','Delts','Deltoides'),
  ('anterior-deltoid','muscle','muscle','deltoids',1,'Anterior deltoid','Deltoides anterior','Front delts','Deltoides frontal'),
  ('lateral-deltoid','muscle','muscle','deltoids',2,'Lateral deltoid','Deltoides lateral','Side delts','Deltoides lateral'),
  ('posterior-deltoid','muscle','muscle','deltoids',3,'Posterior deltoid','Deltoides posterior','Rear delts','Deltoides posterior'),
  ('rotator-cuff','group','muscle','shoulders',2,'Rotator cuff','Manguito rotador',null,null),
  ('supraspinatus','muscle','muscle','rotator-cuff',1,'Supraspinatus','Supraespinoso',null,null),
  ('infraspinatus','muscle','muscle','rotator-cuff',2,'Infraspinatus','Infraespinoso',null,null),
  ('teres-minor','muscle','muscle','rotator-cuff',3,'Teres minor','Redondo menor',null,null),
  ('subscapularis','muscle','muscle','rotator-cuff',4,'Subscapularis','Subescapular',null,null),
  -- Chest
  ('pectorals','group','muscle','chest',1,'Pectorals','Pectorales','Pecs','Pectorales'),
  ('pectoralis-major','muscle','muscle','pectorals',1,'Pectoralis major','Pectoral mayor',null,null),
  ('pectoralis-major-clavicular','head','muscle','pectoralis-major',1,'Clavicular head','Porción clavicular','Upper chest','Pecho superior'),
  ('pectoralis-major-sternal','head','muscle','pectoralis-major',2,'Sternal head','Porción esternal','Mid and lower chest','Pecho medio e inferior'),
  ('pectoralis-minor','muscle','muscle','pectorals',2,'Pectoralis minor','Pectoral menor',null,null),
  ('serratus-anterior','muscle','muscle','chest',2,'Serratus anterior','Serrato anterior',null,null),
  -- Back
  ('latissimus-dorsi','muscle','muscle','back',1,'Latissimus dorsi','Dorsal ancho','Lats','Dorsales'),
  ('teres-major','muscle','muscle','back',2,'Teres major','Redondo mayor',null,null),
  ('trapezius','muscle','muscle','back',3,'Trapezius','Trapecio','Traps','Trapecios'),
  ('trapezius-upper','head','muscle','trapezius',1,'Upper trapezius','Trapecio superior',null,null),
  ('trapezius-middle','head','muscle','trapezius',2,'Middle trapezius','Trapecio medio',null,null),
  ('trapezius-lower','head','muscle','trapezius',3,'Lower trapezius','Trapecio inferior',null,null),
  ('rhomboids','muscle','muscle','back',4,'Rhomboids','Romboides',null,null),
  ('erector-spinae','group','muscle','back',5,'Erector spinae','Erectores de la columna','Lower back','Zona lumbar'),
  -- Arms
  ('upper-arm-front','group','muscle','arms',1,'Upper arm, front','Brazo, parte anterior',null,null),
  ('biceps-brachii','muscle','muscle','upper-arm-front',1,'Biceps brachii','Bíceps braquial','Biceps','Bíceps'),
  ('brachialis','muscle','muscle','upper-arm-front',2,'Brachialis','Braquial',null,null),
  ('upper-arm-back','group','muscle','arms',2,'Upper arm, back','Brazo, parte posterior',null,null),
  ('triceps-brachii','muscle','muscle','upper-arm-back',1,'Triceps brachii','Tríceps braquial','Triceps','Tríceps'),
  ('triceps-long-head','head','muscle','triceps-brachii',1,'Long head','Cabeza larga',null,null),
  ('triceps-lateral-head','head','muscle','triceps-brachii',2,'Lateral head','Cabeza lateral',null,null),
  ('triceps-medial-head','head','muscle','triceps-brachii',3,'Medial head','Cabeza medial',null,null),
  ('forearm','group','muscle','arms',3,'Forearm','Antebrazo','Forearms','Antebrazos'),
  ('forearm-flexors','muscle','muscle','forearm',1,'Forearm flexors','Flexores del antebrazo','Wrist flexors','Flexores de muñeca'),
  ('forearm-extensors','muscle','muscle','forearm',2,'Forearm extensors','Extensores del antebrazo','Wrist extensors','Extensores de muñeca'),
  ('brachioradialis','muscle','muscle','forearm',3,'Brachioradialis','Braquiorradial',null,null),
  -- Abdomen
  ('abdominals','group','muscle','abdomen',1,'Abdominals','Abdominales','Abs','Abdominales'),
  ('rectus-abdominis','muscle','muscle','abdominals',1,'Rectus abdominis','Recto abdominal','Six-pack','Tableta'),
  ('transversus-abdominis','muscle','muscle','abdominals',2,'Transversus abdominis','Transverso abdominal',null,null),
  ('obliques','group','muscle','abdominals',3,'Obliques','Oblicuos',null,null),
  ('external-oblique','muscle','muscle','obliques',1,'External oblique','Oblicuo externo',null,null),
  ('internal-oblique','muscle','muscle','obliques',2,'Internal oblique','Oblicuo interno',null,null),
  -- Hips
  ('glutes','group','muscle','hips',1,'Glutes','Glúteos',null,null),
  ('gluteus-maximus','muscle','muscle','glutes',1,'Gluteus maximus','Glúteo mayor',null,null),
  ('gluteus-medius','muscle','muscle','glutes',2,'Gluteus medius','Glúteo medio',null,null),
  ('gluteus-minimus','muscle','muscle','glutes',3,'Gluteus minimus','Glúteo menor',null,null),
  ('adductors','group','muscle','hips',2,'Adductors','Aductores','Inner thighs','Cara interna del muslo'),
  ('adductor-magnus','muscle','muscle','adductors',1,'Adductor magnus','Aductor mayor',null,null),
  ('adductor-longus','muscle','muscle','adductors',2,'Adductor longus','Aductor largo',null,null),
  ('adductor-brevis','muscle','muscle','adductors',3,'Adductor brevis','Aductor corto',null,null),
  ('gracilis','muscle','muscle','adductors',4,'Gracilis','Grácil',null,null),
  ('hip-flexor-muscles','group','muscle','hips',3,'Hip flexor muscles','Músculos flexores de la cadera',null,null),
  ('iliopsoas','muscle','muscle','hip-flexor-muscles',1,'Iliopsoas','Iliopsoas',null,null),
  ('tensor-fasciae-latae','muscle','muscle','hip-flexor-muscles',2,'Tensor fasciae latae','Tensor de la fascia lata',null,null),
  ('sartorius','muscle','muscle','hip-flexor-muscles',3,'Sartorius','Sartorio',null,null),
  -- Legs
  ('quadriceps','group','muscle','legs',1,'Quadriceps','Cuádriceps','Quads','Cuádriceps'),
  ('rectus-femoris','muscle','muscle','quadriceps',1,'Rectus femoris','Recto femoral',null,null),
  ('vastus-lateralis','muscle','muscle','quadriceps',2,'Vastus lateralis','Vasto lateral',null,null),
  ('vastus-medialis','muscle','muscle','quadriceps',3,'Vastus medialis','Vasto medial',null,null),
  ('vastus-intermedius','muscle','muscle','quadriceps',4,'Vastus intermedius','Vasto intermedio',null,null),
  ('hamstrings','group','muscle','legs',2,'Hamstrings','Isquiotibiales','Hammies','Femorales'),
  ('biceps-femoris','muscle','muscle','hamstrings',1,'Biceps femoris','Bíceps femoral',null,null),
  ('semitendinosus','muscle','muscle','hamstrings',2,'Semitendinosus','Semitendinoso',null,null),
  ('semimembranosus','muscle','muscle','hamstrings',3,'Semimembranosus','Semimembranoso',null,null),
  ('calves','group','muscle','legs',3,'Calves','Pantorrillas','Calves','Gemelos'),
  ('gastrocnemius','muscle','muscle','calves',1,'Gastrocnemius','Gastrocnemio',null,null),
  ('soleus','muscle','muscle','calves',2,'Soleus','Sóleo',null,null),
  ('lower-leg-front','group','muscle','legs',4,'Shin and outer lower leg','Espinilla y cara externa de la pierna',null,null),
  ('tibialis-anterior','muscle','muscle','lower-leg-front',1,'Tibialis anterior','Tibial anterior','Shins','Espinillas'),
  ('peroneals','muscle','muscle','lower-leg-front',2,'Peroneals','Peroneos',null,null),
  -- Non-muscle nodes
  ('ankle','region','joint',null,20,'Ankle','Tobillo',null,null),
  ('wrist','region','joint',null,21,'Wrist','Muñeca',null,null),
  ('hand','region','area',null,22,'Hand','Mano',null,null),
  ('foot','region','area',null,23,'Foot','Pie',null,null),
  ('cardiovascular-system','region','system',null,24,'Cardiovascular system','Sistema cardiovascular','Cardio','Cardio')
) as v(id, level, kind, parent, sort, en, es, cen, ces);

select public.rebuild_muscle_paths();

insert into public.muscle_sets (id, names) values
  ('core',              '{"en":"Core","es":"Core (zona media)"}'),
  ('hip-flexors',       '{"en":"Hip flexors","es":"Flexores de cadera"}'),
  ('hip-abductors',     '{"en":"Hip abductors","es":"Abductores de cadera"}'),
  ('upper-back',        '{"en":"Upper back","es":"Espalda alta"}'),
  ('grip',              '{"en":"Grip","es":"Agarre"}'),
  ('ankle-stabilizers', '{"en":"Ankle stabilizers","es":"Estabilizadores del tobillo"}');

insert into public.muscle_set_members (set_id, muscle_id) values
  ('core','rectus-abdominis'), ('core','external-oblique'), ('core','internal-oblique'),
  ('core','transversus-abdominis'), ('core','erector-spinae'),
  ('hip-flexors','iliopsoas'), ('hip-flexors','rectus-femoris'), ('hip-flexors','tensor-fasciae-latae'), ('hip-flexors','sartorius'),
  ('hip-abductors','gluteus-medius'), ('hip-abductors','gluteus-minimus'), ('hip-abductors','tensor-fasciae-latae'),
  ('upper-back','trapezius-middle'), ('upper-back','trapezius-lower'), ('upper-back','rhomboids'),
  ('upper-back','posterior-deltoid'), ('upper-back','teres-major'),
  ('grip','forearm-flexors'), ('grip','hand'),
  ('ankle-stabilizers','tibialis-anterior'), ('ankle-stabilizers','peroneals'), ('ankle-stabilizers','ankle');

-- Every muscle term used in exercises.json (target, muscle_group, secondary_muscles): 50 terms.
insert into public.muscle_aliases (term, muscle_id, set_id, confidence, note) values
  ('abdominals','abdominals',null,'exact',null),
  ('abductors',null,'hip-abductors','exact',null),
  ('abs','abdominals',null,'synonym','Mapped to the group, not rectus abdominis. Open decision.'),
  ('adductors','adductors',null,'exact',null),
  ('ankle stabilizers',null,'ankle-stabilizers','interpreted',null),
  ('ankles','ankle',null,'exact','Joint, not a muscle.'),
  ('back','back',null,'broader','Region only; the data does not say which back muscle.'),
  ('biceps','biceps-brachii',null,'exact',null),
  ('brachialis','brachialis',null,'exact',null),
  ('calves','calves',null,'exact',null),
  ('cardiovascular system','cardiovascular-system',null,'exact','Target of all cardio exercises.'),
  ('chest','chest',null,'broader','Region only.'),
  ('core',null,'core','exact',null),
  ('deltoids','deltoids',null,'exact',null),
  ('delts','deltoids',null,'synonym',null),
  ('feet','foot',null,'exact','Area, not a muscle.'),
  ('forearms','forearm',null,'exact',null),
  ('glutes','glutes',null,'exact',null),
  ('grip muscles',null,'grip','exact',null),
  ('groin','adductors',null,'synonym',null),
  ('hamstrings','hamstrings',null,'exact',null),
  ('hands','hand',null,'exact','Area, not a muscle.'),
  ('hip flexors',null,'hip-flexors','exact',null),
  ('inner thighs','adductors',null,'synonym',null),
  ('latissimus dorsi','latissimus-dorsi',null,'exact',null),
  ('lats','latissimus-dorsi',null,'synonym',null),
  ('levator scapulae','levator-scapulae',null,'exact',null),
  ('lower abs','rectus-abdominis',null,'interpreted','"Lower" is not a separate muscle.'),
  ('lower back','erector-spinae',null,'interpreted','A region; erector spinae is the muscle trained.'),
  ('obliques','obliques',null,'exact',null),
  ('pectorals','pectorals',null,'exact',null),
  ('quadriceps','quadriceps',null,'exact',null),
  ('quads','quadriceps',null,'synonym',null),
  ('rear deltoids','posterior-deltoid',null,'synonym',null),
  ('rhomboids','rhomboids',null,'exact',null),
  ('rotator cuff','rotator-cuff',null,'exact',null),
  ('serratus anterior','serratus-anterior',null,'exact',null),
  ('shins','tibialis-anterior',null,'interpreted',null),
  ('shoulders','shoulders',null,'broader','Region only; usually means deltoids. Open decision.'),
  ('soleus','soleus',null,'exact',null),
  ('spine','erector-spinae',null,'interpreted','"Spine" targets in this dataset are back extensions.'),
  ('sternocleidomastoid','sternocleidomastoid',null,'exact',null),
  ('trapezius','trapezius',null,'exact',null),
  ('traps','trapezius',null,'synonym',null),
  ('triceps','triceps-brachii',null,'exact',null),
  ('upper back',null,'upper-back','exact',null),
  ('upper chest','pectoralis-major-clavicular',null,'synonym',null),
  ('wrist extensors','forearm-extensors',null,'synonym',null),
  ('wrist flexors','forearm-flexors',null,'synonym',null),
  ('wrists','wrist',null,'exact','Joint, not a muscle.');
